import Navbar from "../components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Provider from "@/components/Provider";

export const metadata = {
  title: "SellFast",
  description: "Generated by create next app",
};

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
